1) EMPEZAR CON EL ARCANOID, ADAPTAR EL QUE YA TENGO AL ESTILO DE MAPA DEL GEOMETRY DASH ,AÑADIRLE UN SISTEMA DE PUNTUACIONES CORRECTO ,HACERLO EN PHP Y CONEXIONES PARA MANDAR PUNTUACIONES
CONFIGURARSE CON EL LOGUEO DE LA PAGINA,NAVEGADOR...ETC.
2) EMPEZAR CON ESTAS PAGINAS O REVISAR SI ME FALTA ALGUNA COSA MAS IMPORTANTE.
3) MIRAR QUE SERVICIOS PUEDO PONER EN EL WEB SERVICE.